name: PR Vishal

on: 
  pull_request:
    types: [opened, reopened, edited]

jobs:
  pr_title:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      env:
        PR_TITLE: ${{ toJson(github) }}
      run: echo "$PR_TITLE"
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
