name: PR Vishal

on: 
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  pr_title:

    runs-on: ubuntu-latest

    steps:
    - name: Check PR Title
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: "[[ $PR_TITLE =~ FRESHID[-_]\\d* ]]"
